[package]
name    = "tun"
version = "0.5.1"
edition = "2018"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "TUN device creation and handling."
repository  = "https://github.com/meh/rust-tun"
keywords    = ["tun", "network", "tunnel", "bindings"]

[dependencies]
libc      = "0.2"
thiserror = "1"

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "ios"))'.dependencies]
mio        = { version = "0.6", optional = true }
tokio      = { version = "0.2", features = ["full"], optional = true }
tokio-util = { version = "0.3", features = ["codec"], optional = true }
bytes      = { version = "0.5", optional = true }
byteorder  = { version = "1.3", optional = true }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
ioctl      = { version = "0.6", package = "ioctl-sys" }

# MARKER BEGIN
[target.'cfg(any(target_os = "windows"))'.dependencies]
wintun = "0.2.1"
# MARKER END

[dev-dependencies]
packet     = "0.1"
futures    = "0.3.1"

[features]
async = ["tokio", "tokio-util", "mio", "bytes", "byteorder"]

[[example]]
name = "read-async"
required-features = [ "async" ]

[[example]]
name = "read-async-codec"
required-features = [ "async" ]

[[example]]
name = "ping-tun"
required-features = [ "async" ]
